# Generated by Django 5.0 on 2025-12-12 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='金额')),
                ('category', models.CharField(choices=[('Salary', '员工工资'), ('Maintenance', '维修费用'), ('Utilities', '水电费'), ('Other', '其他支出')], max_length=50, verbose_name='支出类别')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='金额')),
                ('source', models.CharField(choices=[('Room', '客房收入'), ('Food', '餐饮收入'), ('Other', '其他收入')], max_length=50, verbose_name='收入来源')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '收入',
                'verbose_name_plural': '收入',
            },
        ),
    ]
