# Generated by Django 5.0 on 2025-12-12 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='房间号必须是三位数字，如：101、202、303', regex='^\\d{3}$')], verbose_name='房间号')),
                ('room_type', models.CharField(choices=[('Single', '单人间'), ('Double', '双人间'), ('Suite', '套房'), ('Deluxe', '豪华间')], max_length=50, verbose_name='房间类型')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='价格')),
                ('facilities', models.TextField(verbose_name='设施')),
                ('status', models.CharField(choices=[('Available', '空闲'), ('Booked', '已预订'), ('Occupied', '已入住'), ('Maintenance', '维修中')], default='Available', max_length=20, verbose_name='状态')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('capacity', models.IntegerField(verbose_name='容纳人数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='房间主图')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
    ]
