# Generated by Django 5.0 on 2025-12-12 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(choices=[('前台', '前台'), ('后厨', '后厨'), ('保洁', '保洁'), ('保安', '保安'), ('经理', '经理')], max_length=100, verbose_name='职位')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='联系方式')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='工资')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('status', models.CharField(choices=[('在职', '在职'), ('离职', '离职')], default='在职', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
    ]
