# Generated by Django 5.0 on 2025-12-12 15:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='入住日期')),
                ('check_out_date', models.DateField(verbose_name='离店日期')),
                ('number_of_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='入住人数')),
                ('special_requests', models.TextField(blank=True, verbose_name='特殊要求')),
                ('status', models.CharField(choices=[('Booked', '已预定'), ('CheckedIn', '已入住'), ('CheckedOut', '已离店'), ('Refunded', '已退订')], default='Booked', max_length=20, verbose_name='预订状态')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='天数×房价自动计算', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='已付金额')),
                ('income_recorded', models.BooleanField(default=False, verbose_name='已记录收入')),
                ('refund_recorded', models.BooleanField(default=False, verbose_name='已退款')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='退款金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='客户')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '预订',
                'verbose_name_plural': '预订',
                'ordering': ['-check_in_date'],
            },
        ),
    ]
