# Generated by Django 5.0 on 2025-12-12 15:21

import customers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=18, unique=True, validators=[customers.models.validate_id_number], verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='联系方式')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
    ]
